import { db } from './firebase-init.js';
import { collection, addDoc, deleteDoc, doc, onSnapshot, query, serverTimestamp, getDocs } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
const $=(id)=>document.getElementById(id);const toast=(m)=>{const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)};
let allResults=[];
$('addTeamBtn').onclick=async()=>{const name=$('teamName').value.trim();if(!name)return toast('Digite o nome da equipe.');await addDoc(collection(db,'teams'),{name,info:$('teamInfo').value.trim(),createdAt:serverTimestamp()});$('teamName').value='';$('teamInfo').value='';toast('Equipe adicionada.');};
onSnapshot(query(collection(db,'teams')),snap=>{const teams=[];snap.forEach(d=>teams.push({id:d.id,...d.data()}));teams.sort((a,b)=>a.name.localeCompare(b.name));$('teamList').innerHTML=teams.map(t=>`<div class="admin-item"><div><strong>${t.name}</strong><br><span class="muted">${t.info||''}</span></div><button class="btn red" data-delteam="${t.id}">Excluir</button></div>`).join('');document.querySelectorAll('[data-delteam]').forEach(b=>b.onclick=async()=>{if(confirm('Excluir equipe?')) await deleteDoc(doc(db,'teams',b.dataset.delteam));});});
onSnapshot(query(collection(db,'results')),snap=>{allResults=[];snap.forEach(d=>allResults.push({id:d.id,...d.data()}));allResults.sort((a,b)=>new Date(b.createdAtLocal||0)-new Date(a.createdAtLocal||0));$('resultsBody').innerHTML=allResults.map(r=>`<tr><td>${r.teamName}</td><td>${r.round}</td><td><strong>${r.score}</strong></td><td>${new Date(r.createdAtLocal).toLocaleString('pt-BR')}</td><td><button class="btn red" data-delres="${r.id}">Excluir</button></td></tr>`).join('');document.querySelectorAll('[data-delres]').forEach(b=>b.onclick=async()=>{if(confirm('Excluir resultado?')) await deleteDoc(doc(db,'results',b.dataset.delres));});});
$('exportBtn').onclick=()=>{const rows=[['Equipe','Round','Pontos','Juiz','Data']].concat(allResults.map(r=>[r.teamName,r.round,r.score,r.judge||'',r.createdAtLocal||'']));const csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='resultados-fll-2026.csv';a.click();};
$('deleteAllBtn').onclick=async()=>{if(!confirm('Apagar TODOS os resultados?'))return;const snap=await getDocs(collection(db,'results'));await Promise.all(snap.docs.map(d=>deleteDoc(doc(db,'results',d.id))));toast('Resultados apagados.');};
